import type { PrismaClient } from '../../src/generated/prisma';
export type SeedDb = PrismaClient;
export type TopicCategory = 'GRAMMAR' | 'VOCABULARY' | 'READING' | 'LISTENING' | 'WRITING' | 'SPEAKING';
export type ExamLevel = 'B1' | 'B2' | 'C1' | 'B1_B2' | 'B1_C1';
export type QuestionDifficulty = 'EASY' | 'MEDIUM' | 'HARD';
export type SourceType = 'OFFICIAL_SAMPLE' | 'RECONSTRUCTED' | 'SYNTHETIC_MOCK' | 'ORIGINAL' | 'AI_GENERATED';
export type DatasetOption = { key: string; content: string; isCorrect: boolean; explanation?: string };
export type DatasetGroup = { key: string; kind: 'PASSAGE' | 'LISTENING' | 'OTHER'; title?: string; stimulus?: string; audioReference?: string; transcript?: string; sourceReference?: string; provenanceNotes?: string };
export type DatasetQuestion = { key: string; partCode?: string; sectionCode?: string; questionTypeCode: string; topicCodes: string[]; content: string; instruction?: string; context?: string; level: ExamLevel; difficulty?: QuestionDifficulty; hint1?: string; hint2?: string; hint3?: string; explanation?: string; options?: DatasetOption[]; groupKey?: string; sourceType?: SourceType; sourceYear?: number; sourceCenter?: string; sourceOrg?: string; sourceReference?: string; provenanceNotes?: string };
export type DatasetSection = { code: string; name: string; position: number; questionCount?: number; partCount?: number; passageCount?: number; taskCount?: number; durationMinutes?: number };
export type ExamDataset = { key: string; examTypeCode: 'HCMUS_MASTER_ENTRANCE' | 'VSTEP' | 'B1' | 'B2'; title: string; source: string; sourceType: SourceType; sourceYear?: number; sourceCenter?: string; sourceOrg?: string; sourceReference?: string; sourceUrl?: string; provenanceNotes: string; detectedLevel: ExamLevel; blueprintKey?: string; sections: DatasetSection[]; questions: DatasetQuestion[]; groups?: DatasetGroup[] };
export function validateDataset(dataset: ExamDataset): string[] { const errors: string[] = []; const fail = (m: string) => errors.push(`Dataset ${dataset.key}: ${m}`); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(dataset.key)) fail('key must be kebab-case'); if (!dataset.provenanceNotes?.trim()) fail('provenanceNotes is required'); if (dataset.sourceType === 'SYNTHETIC_MOCK' && /real exam|past exam|actual exam/i.test(`${dataset.source} ${dataset.provenanceNotes}`)) fail('synthetic content cannot claim to be a real exam'); const sections = new Set(dataset.sections.map(s => s.code)); const keys = new Set<string>(); const groups = new Set((dataset.groups ?? []).map(g => g.key)); if (groups.size !== (dataset.groups ?? []).length) fail('duplicate group keys'); for (const q of dataset.questions) { if (keys.has(q.key)) fail(`duplicate question key ${q.key}`); keys.add(q.key); if (!q.sectionCode && !q.partCode || !sections.has(q.sectionCode ?? q.partCode!)) fail(`question ${q.key} references missing section`); if (!q.topicCodes.length) fail(`question ${q.key} requires a topic`); if (!q.explanation?.trim() || !q.hint1?.trim()) fail(`question ${q.key} requires explanation and hint1`); if (q.groupKey && !groups.has(q.groupKey)) fail(`question ${q.key} references missing group ${q.groupKey}`); const options = q.options ?? []; if (new Set(options.map(o => o.key)).size !== options.length) fail(`question ${q.key} has duplicate option keys`); if (options.length > 0 && (options.length < 2 || options.filter(o => o.isCorrect).length !== 1)) fail(`question ${q.key} must have exactly one correct option and at least two options`); } return errors; }
export function assertValidDataset(dataset: ExamDataset): void { const errors = validateDataset(dataset); if (errors.length) throw new Error(errors.join('\n')); }
