'use client';

import { Suspense, useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { api } from '@/lib/api-client';
import { Badge, Button, Card, SectionTitle } from '@/components/ui';
import { StudentShell } from '@/components/shells';
interface Attempt { id: string; isCorrect: boolean | null; hintLevelUsed: number; question: { id: string; content: string; explanation?: string | null; options: Array<{ id: string; optionKey: string; content: string; isCorrect: boolean; explanation?: string | null }>; questionType?: { name: string } | null }; selectedOption?: { id: string; optionKey: string; content: string } | null; }
interface Session { type: string; status: string; score: number; correctCount: number; totalQuestions: number; }
function Inner() { const params = useSearchParams(); const id = params.get('sessionId') ?? ''; const [session, setSession] = useState<Session | null>(null); const [attempts, setAttempts] = useState<Attempt[]>([]); const [error, setError] = useState<string | null>(null); useEffect(() => { if (!id) return; Promise.all([api.getPracticeSession(id), api.listAttempts(id)]).then(([s, a]) => { setSession(s as Session); setAttempts(a as Attempt[]); }).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load result')); }, [id]); if (!id) return <StudentShell><Card><p>Missing session.</p></Card></StudentShell>; if (error) return <StudentShell><Card><p role="alert" className="text-rose-700">{error}</p></Card></StudentShell>; if (!session) return <StudentShell><p className="text-slate-500">Loading result…</p></StudentShell>; const weak = attempts.filter((a) => !a.isCorrect); return <StudentShell><SectionTitle eyebrow={session.type === 'MOCK_EXAM' ? 'Mock exam result' : 'Practice result'} title={`${Math.round(session.score * 100)}%`} description={`${session.correctCount} of ${session.totalQuestions} answers correct. Review the gaps, then choose your next focused step.`} action={<Badge tone={session.score >= .7 ? 'green' : 'amber'}>{session.status}</Badge>} /><div className="grid gap-4 sm:grid-cols-3"><Card><p className="text-sm text-slate-500">Score</p><p className="mt-2 text-3xl font-bold">{Math.round(session.score * 100)}%</p></Card><Card><p className="text-sm text-slate-500">Questions</p><p className="mt-2 text-3xl font-bold">{session.correctCount}/{session.totalQuestions}</p></Card><Card><p className="text-sm text-slate-500">Needs review</p><p className="mt-2 text-3xl font-bold">{weak.length}</p></Card></div><div className="mt-5 flex flex-wrap gap-3"><Link className="inline-flex min-h-11 items-center rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white" href={weak.length ? '/mistakes' : '/learn'}>{weak.length ? 'Review mistakes →' : 'Practice weak topics →'}</Link><Link className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 px-5 text-sm font-semibold text-slate-800" href="/dashboard">Back to Today</Link></div><Card className="mt-5"><h2 className="text-lg font-bold">Answer review</h2><div className="mt-4 space-y-3">{attempts.map((a, i) => <details key={a.id} className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold">{i + 1}. {a.isCorrect ? 'Correct' : 'Needs review'} · {a.question.questionType?.name ?? 'Question'}</summary><p className="mt-3 text-sm leading-6 text-slate-700">{a.question.content}</p>{a.question.explanation && <p className="mt-2 text-sm text-slate-500">{a.question.explanation}</p>}</details>)}</div></Card><Button className="mt-5" onClick={() => window.location.href = '/practice'}>Practice another set</Button></StudentShell>; }
export default function ReviewPage() { return <Suspense fallback={<p>Loading…</p>}><Inner /></Suspense>; }
