import { PrismaClient } from './src/generated/prisma';
import { createHash } from 'node:crypto';

const prisma = new PrismaClient();
const dryRun = process.argv.includes('--dry-run');
const stableId = (key: string) => {
  const h = createHash('sha256').update(key).digest('hex').slice(0, 32);
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-${((parseInt(h.slice(16, 18), 16) & 0x3f) | 0x80).toString(16).padStart(2, '0')}${h.slice(18, 20)}-${h.slice(20)}`;
};
const syntheticContext = 'Synthetic content authored for this English exam-prep MVP; not an official exam question.';
const topics = [
  ['GRAMMAR', 'Grammar', 'GRAMMAR'], ['TENSES', 'Tenses', 'GRAMMAR'], ['CONDITIONALS', 'Conditionals', 'GRAMMAR'], ['PRESENT_PERFECT', 'Present Perfect', 'GRAMMAR'],
  ['VOCABULARY', 'Vocabulary', 'VOCABULARY'], ['WORD_FORM', 'Word Form', 'VOCABULARY'], ['COLLOCATION', 'Collocation', 'VOCABULARY'],
  ['MAIN_IDEA', 'Main Idea', 'READING'], ['DETAIL', 'Detail', 'READING'], ['INFERENCE', 'Inference', 'READING'], ['REFERENCE', 'Reference', 'READING'], ['VOCABULARY_IN_CONTEXT', 'Vocabulary in Context', 'READING'], ['AUTHOR_PURPOSE', 'Author Purpose', 'READING'],
  ['LISTENING_DETAIL', 'Listening Detail', 'LISTENING'], ['LISTENING_MAIN_IDEA', 'Listening Main Idea', 'LISTENING'], ['LISTENING_INFERENCE', 'Listening Inference', 'LISTENING'],
  ['LETTER_EMAIL', 'Letter / Email', 'WRITING'], ['AGREE_DISAGREE', 'Agree / Disagree', 'WRITING'], ['DISCUSS_BOTH_SIDES', 'Discuss Both Sides', 'WRITING'],
  ['SOCIAL_INTERACTION', 'Social Interaction', 'SPEAKING'], ['SOLUTION_DISCUSSION', 'Solution Discussion', 'SPEAKING'], ['TOPIC_DEVELOPMENT', 'Topic Development', 'SPEAKING'], ['HOMETOWN', 'Hometown', 'SPEAKING'],
] as const;
const questionTypes = [
  ['MCQ_SINGLE_BLANK', 'MCQ Single Blank', 'GRAMMAR'], ['VOCABULARY_MCQ', 'Vocabulary MCQ', 'VOCABULARY'], ['READING_COMPREHENSION', 'Reading Comprehension', 'READING'],
  ['ANNOUNCEMENT_INSTRUCTION', 'Announcement / Instruction', 'LISTENING'], ['CONVERSATION', 'Conversation', 'LISTENING'], ['TALK_LECTURE', 'Talk / Lecture', 'LISTENING'],
  ['LISTENING_MCQ', 'Listening MCQ', 'LISTENING'], ['LETTER_EMAIL', 'Letter / Email', 'WRITING'], ['ESSAY', 'Essay', 'WRITING'],
  ['SOCIAL_INTERACTION', 'Social Interaction', 'SPEAKING'], ['SOLUTION_DISCUSSION', 'Solution Discussion', 'SPEAKING'], ['TOPIC_DEVELOPMENT', 'Topic Development', 'SPEAKING'],
] as const;
const scopeDefs = [
  ['scope-tenses', 'Tenses', 'TENSES', 1], ['scope-conditionals', 'Conditionals', 'CONDITIONALS', 2], ['scope-present-perfect', 'Present Perfect', 'PRESENT_PERFECT', 3],
  ['scope-word-form', 'Word Form', 'WORD_FORM', 4], ['scope-reading-main-idea', 'Reading Main Idea', 'MAIN_IDEA', 5], ['scope-reading-detail', 'Reading Detail', 'DETAIL', 6],
  ['scope-listening-detail', 'Listening Detail', 'LISTENING_DETAIL', 7], ['scope-formal-email', 'Formal Email Writing', 'LETTER_EMAIL', 8],
] as const;
const lesson = (name: string) => ({ rule: `Use context clues and the target ${name.toLowerCase()} rule before choosing.`, examples: [`A clear context helps apply ${name.toLowerCase()} accurately.`, `Review the sentence meaning before selecting an option.`], commonMistakes: ['Choosing a grammatically possible option that changes the meaning.', 'Ignoring the strongest context clue.'] });

type TopicRow = { id: string; code: string };
type TypeRow = { id: string; code: string };
const maps = { topics: new Map<string, TopicRow>(), types: new Map<string, TypeRow>(), sections: new Map<string, { id: string }>() };

async function ensureCatalog() {
  for (const [code, name, category] of topics) maps.topics.set(code, await prisma.topic.upsert({ where: { code }, update: { name, category }, create: { code, name, category } }));
  for (const [code, name, category] of questionTypes) maps.types.set(code, await prisma.questionType.upsert({ where: { code }, update: { name, category }, create: { code, name, category } }));
}
async function ensureSection(examId: string, code: string, name: string, position: number, questionCount: number, durationMinutes: number) {
  const row = await prisma.examSection.upsert({ where: { examId_code: { examId, code } }, update: { name, position, questionCount, durationMinutes }, create: { examId, code, name, position, questionCount, durationMinutes } });
  maps.sections.set(`${examId}:${code}`, row);
  return row;
}
async function upsertQuestion(key: string, sectionId: string, typeCode: string, topicCode: string, level: 'B1' | 'B2' | 'C1' | 'B1_B2' | 'B1_C1', examId: string | null, groupId?: string) {
  const type = maps.types.get(typeCode)!; const topic = maps.topics.get(topicCode)!; const qid = stableId(`safe-production:question:${key}`);
  const q = await prisma.question.upsert({ where: { id: qid }, update: { examId, examSectionId: sectionId, questionTypeId: type.id, questionGroupId: groupId, contentRole: 'MOCK_EXAM', content: `Synthetic ${typeCode.toLowerCase().replaceAll('_', ' ')} item ${key}: choose the answer supported by the context.`, instruction: 'Choose the best answer.', context: syntheticContext, level, difficulty: 'MEDIUM', hint1: 'Identify the key clue before eliminating distractors.', hint2: 'Compare each option with the context.', hint3: 'Choose the option that matches the intended meaning.', explanation: 'The correct option matches the context and target skill.', ruleStructure: 'Use the context and target structure.', commonMistake: 'Selecting an option without checking the context.', example: 'Read the clue, then select the supported answer.', status: 'PUBLISHED' }, create: { id: qid, examId, examSectionId: sectionId, questionTypeId: type.id, questionGroupId: groupId, contentRole: 'MOCK_EXAM', content: `Synthetic ${typeCode.toLowerCase().replaceAll('_', ' ')} item ${key}: choose the answer supported by the context.`, instruction: 'Choose the best answer.', context: syntheticContext, level, difficulty: 'MEDIUM', hint1: 'Identify the key clue before eliminating distractors.', hint2: 'Compare each option with the context.', hint3: 'Choose the option that matches the intended meaning.', explanation: 'The correct option matches the context and target skill.', ruleStructure: 'Use the context and target structure.', commonMistake: 'Selecting an option without checking the context.', example: 'Read the clue, then select the supported answer.', status: 'PUBLISHED' } });
  await prisma.questionTopic.upsert({ where: { questionId_topicId: { questionId: q.id, topicId: topic.id } }, update: { isPrimary: true, source: 'SYSTEM', confidence: 1 }, create: { questionId: q.id, topicId: topic.id, isPrimary: true, source: 'SYSTEM', confidence: 1 } });
  for (const [optionKey, isCorrect] of [['A', true], ['B', false], ['C', false], ['D', false]] as const) await prisma.questionOption.upsert({ where: { questionId_optionKey: { questionId: q.id, optionKey } }, update: { content: isCorrect ? 'The option supported by the context.' : `Distractor ${optionKey}: it does not fit the context.`, isCorrect, explanation: isCorrect ? 'This option fits the context.' : 'This option is not supported by the context.', position: optionKey.charCodeAt(0) - 65 }, create: { id: stableId(`safe-production:option:${key}:${optionKey}`), questionId: q.id, optionKey, content: isCorrect ? 'The option supported by the context.' : `Distractor ${optionKey}: it does not fit the context.`, isCorrect, explanation: isCorrect ? 'This option fits the context.' : 'This option is not supported by the context.', position: optionKey.charCodeAt(0) - 65 } });
}
async function ensureBlueprint(key: string, examTypeId: string, name: string, source: string, durationMinutes: number, status: 'ACTIVE' | 'DRAFT', examId: string, itemDefs: Array<[string, string, string, number, string, string, number]>) {
  const bp = await prisma.examBlueprint.upsert({ where: { externalKey: `safe:${key}` }, update: { examTypeId, name, version: 'safe-1', source, provenance: 'SYNTHETIC_MOCK', durationMinutes, totalScore: 100, status, sourceExamCount: 0 }, create: { externalKey: `safe:${key}`, examTypeId, name, version: 'safe-1', source, provenance: 'SYNTHETIC_MOCK', durationMinutes, totalScore: 100, status, sourceExamCount: 0 } });
  for (const [i, [code, sectionCode, title, count, typeCode, topicCode, weight]] of itemDefs.entries()) {
    const section = await prisma.blueprintSection.upsert({ where: { blueprintId_code: { blueprintId: bp.id, code: sectionCode } }, update: { title, position: i + 1, durationMinutes: sectionCode === 'READING' ? 60 : undefined }, create: { blueprintId: bp.id, code: sectionCode, title, position: i + 1, durationMinutes: sectionCode === 'READING' ? 60 : undefined } });
    const part = await prisma.blueprintPart.upsert({ where: { sectionId_code: { sectionId: section.id, code } }, update: { title, position: 1, questionCount: count, groupCount: sectionCode === 'READING' ? 4 : undefined, questionsPerGroup: sectionCode === 'READING' ? 10 : undefined, groupingSemantics: sectionCode === 'READING' ? '4 passages x 10 questions' : undefined }, create: { externalKey: `safe:${key}:part:${code}`, sectionId: section.id, code, title, position: 1, questionCount: count, groupCount: sectionCode === 'READING' ? 4 : undefined, questionsPerGroup: sectionCode === 'READING' ? 10 : undefined, groupingSemantics: sectionCode === 'READING' ? '4 passages x 10 questions' : undefined } });
    const type = maps.types.get(typeCode)!; const topic = maps.topics.get(topicCode)!;
    await prisma.blueprintSlot.upsert({ where: { partId_code: { partId: part.id, code: 'POOL' } }, update: { title, position: 1, questionTypeId: type.id, topicId: topic.id, count, level: examTypeId === (await prisma.examType.findUniqueOrThrow({ where: { code: 'VSTEP' } })).id ? 'B1_C1' : 'B1_B2', selectionPolicy: { mode: 'pool' } }, create: { externalKey: `safe:${key}:slot:${code}`, partId: part.id, code: 'POOL', title, position: 1, questionTypeId: type.id, topicId: topic.id, count, level: examTypeId === (await prisma.examType.findUniqueOrThrow({ where: { code: 'VSTEP' } })).id ? 'B1_C1' : 'B1_B2', selectionPolicy: { mode: 'pool' } } });
    await prisma.examBlueprintItem.upsert({ where: { id: stableId(`safe-production:item:${key}:${code}`) }, update: { blueprintId: bp.id, sectionCode, questionTypeId: type.id, topicId: topic.id, questionCount: count, weight }, create: { id: stableId(`safe-production:item:${key}:${code}`), blueprintId: bp.id, sectionCode, questionTypeId: type.id, topicId: topic.id, questionCount: count, weight } });
  }
  return bp;
}
async function main() {
  await ensureCatalog();
  const vstep = await prisma.examType.findUniqueOrThrow({ where: { code: 'VSTEP' } });
  const hcmus = await prisma.examType.findUniqueOrThrow({ where: { code: 'HCMUS_MASTER_ENTRANCE' } });
  if (dryRun) { console.log(JSON.stringify({ mode: 'dry-run', plannedScopes: scopeDefs.length, plannedQuestionsPerScope: 5, plannedVstepReading: 40, plannedVstepListening: 35, plannedVstepWriting: 2, plannedVstepSpeaking: 3, plannedHcmus: 72 })); return; }
  for (const [code, name, topicCode, position] of scopeDefs) { const topic = maps.topics.get(topicCode)!; const scope = await prisma.learningScope.upsert({ where: { code }, update: { name, topicId: topic.id, lesson: lesson(name), position, isActive: true }, create: { code, name, topicId: topic.id, lesson: lesson(name), position, isActive: true } }); void scope; const section = await prisma.examSection.findFirst({ where: { examTypeId: vstep.id, code: topicCode.startsWith('LISTENING') ? 'LISTENING' : topicCode === 'LETTER_EMAIL' ? 'WRITING' : 'READING' } }); if (!section) throw new Error(`Missing section for scope ${code}`); const type = topicCode === 'LETTER_EMAIL' ? 'LETTER_EMAIL' : topicCode.startsWith('LISTENING') ? 'LISTENING_MCQ' : topicCode === 'WORD_FORM' ? 'VOCABULARY_MCQ' : topicCode === 'TENSES' || topicCode === 'CONDITIONALS' || topicCode === 'PRESENT_PERFECT' ? 'MCQ_SINGLE_BLANK' : 'READING_COMPREHENSION'; for (let i = 1; i <= 5; i++) await upsertQuestion(`learn:${code}:${i}`, section.id, type, topicCode, 'B1_B2', null); }
  const vExam = await prisma.exam.upsert({ where: { id: stableId('safe-production:exam:vstep') }, update: { examTypeId: vstep.id, title: 'VSTEP 3-5 Synthetic Full Mock Pool', source: 'Synthetic pool aligned to verified VSTEP format; not an official paper', detectedLevel: 'B1_C1', durationMinutes: 172, totalScore: 100, status: 'REVIEWED' }, create: { id: stableId('safe-production:exam:vstep'), examTypeId: vstep.id, title: 'VSTEP 3-5 Synthetic Full Mock Pool', source: 'Synthetic pool aligned to verified VSTEP format; not an official paper', detectedLevel: 'B1_C1', durationMinutes: 172, totalScore: 100, status: 'REVIEWED' } });
  const hExam = await prisma.exam.upsert({ where: { id: stableId('safe-production:exam:hcmus') }, update: { examTypeId: hcmus.id, title: 'HCMUS 2026 Conservative Synthetic Practice Pool', source: 'Synthetic four-skill practice informed only by verified current 2026 timing; not an official paper', detectedLevel: 'B1_B2', durationMinutes: 120, totalScore: 100, status: 'REVIEWED' }, create: { id: stableId('safe-production:exam:hcmus'), examTypeId: hcmus.id, title: 'HCMUS 2026 Conservative Synthetic Practice Pool', source: 'Synthetic four-skill practice informed only by verified current 2026 timing; not an official paper', detectedLevel: 'B1_B2', durationMinutes: 120, totalScore: 100, status: 'REVIEWED' } });
  const vSecs = { listening: await ensureSection(vExam.id, 'LISTENING', 'Listening: three parts', 1, 35, 40), reading: await ensureSection(vExam.id, 'READING', 'Reading: four passages', 2, 40, 60), writing: await ensureSection(vExam.id, 'WRITING', 'Writing: email and essay', 3, 2, 60), speaking: await ensureSection(vExam.id, 'SPEAKING', 'Speaking: three parts', 4, 3, 12) };
  const hSecs = { vocab: await ensureSection(hExam.id, 'VOCABULARY_READING', 'Conservative vocabulary and reading practice', 1, 20, 30), grammar: await ensureSection(hExam.id, 'GRAMMAR_USE_OF_ENGLISH_WRITING', 'Conservative grammar and use practice', 2, 30, 45), listening: await ensureSection(hExam.id, 'LISTENING', 'Conservative listening practice', 3, 20, 25), speaking: await ensureSection(hExam.id, 'SPEAKING', 'Conservative speaking practice', 4, 2, 20) };
  for (const [part, topic, type, count] of [['listening', 'LISTENING_DETAIL', 'ANNOUNCEMENT_INSTRUCTION', 8], ['listening', 'LISTENING_DETAIL', 'CONVERSATION', 12], ['listening', 'LISTENING_MAIN_IDEA', 'TALK_LECTURE', 15], ['reading', 'MAIN_IDEA', 'READING_COMPREHENSION', 40], ['writing', 'LETTER_EMAIL', 'LETTER_EMAIL', 1], ['writing', 'DISCUSS_BOTH_SIDES', 'ESSAY', 1], ['speaking', 'SOCIAL_INTERACTION', 'SOCIAL_INTERACTION', 1], ['speaking', 'SOLUTION_DISCUSSION', 'SOLUTION_DISCUSSION', 1], ['speaking', 'TOPIC_DEVELOPMENT', 'TOPIC_DEVELOPMENT', 1]] as const) { const section = vSecs[part]; let groupIds: (string | undefined)[] = [undefined]; if (part === 'reading') { groupIds = []; for (let g = 1; g <= 4; g++) { const group = await prisma.questionGroup.upsert({ where: { externalKey: `safe:vstep:passage:${g}` }, update: { examId: vExam.id, code: `PASSAGE_${g}`, position: g, stimulus: `Synthetic reading passage ${g}; approximately 475-625 words.`, groupSize: 10, questionsPerGroup: 10, selectionPolicy: { mode: 'fixed_passage' } }, create: { externalKey: `safe:vstep:passage:${g}`, examId: vExam.id, code: `PASSAGE_${g}`, position: g, stimulus: `Synthetic reading passage ${g}; approximately 475-625 words.`, groupSize: 10, questionsPerGroup: 10, selectionPolicy: { mode: 'fixed_passage' } } }); for (let i = 1; i <= 10; i++) groupIds.push(group.id); } } for (let i = 1; i <= count; i++) await upsertQuestion(`vstep:${part}:${type}:${i}`, section.id, type, topic, 'B1_C1', vExam.id, part === 'reading' ? groupIds[i] : undefined); }
  await ensureBlueprint('vstep-full', vstep.id, 'VSTEP 3-5 Full Synthetic Mock', 'Synthetic mock aligned to verified VSTEP format; not an official paper', 172, 'ACTIVE', vExam.id, [['LISTENING', 'LISTENING', 'Listening 3 parts / 35 MCQ', 35, 'LISTENING_MCQ', 'LISTENING_DETAIL', 0.4375], ['READING', 'READING', 'Reading 4 passages x 10 MCQ', 40, 'READING_COMPREHENSION', 'MAIN_IDEA', 0.5], ['WRITING_EMAIL', 'WRITING', 'Writing email >=120 words', 1, 'LETTER_EMAIL', 'LETTER_EMAIL', 0.0125], ['WRITING_ESSAY', 'WRITING', 'Writing essay >=250 words', 1, 'ESSAY', 'DISCUSS_BOTH_SIDES', 0.0125], ['SPEAKING_SOCIAL', 'SPEAKING', 'Speaking social interaction', 1, 'SOCIAL_INTERACTION', 'SOCIAL_INTERACTION', 0.0125], ['SPEAKING_SOLUTION', 'SPEAKING', 'Speaking solution discussion', 1, 'SOLUTION_DISCUSSION', 'SOLUTION_DISCUSSION', 0.0125], ['SPEAKING_TOPIC', 'SPEAKING', 'Speaking topic development', 1, 'TOPIC_DEVELOPMENT', 'TOPIC_DEVELOPMENT', 0.0125]]);
  for (const [section, topic, type, count] of [['vocab', 'VOCABULARY', 'VOCABULARY_MCQ', 20], ['grammar', 'GRAMMAR', 'MCQ_SINGLE_BLANK', 30], ['listening', 'LISTENING_DETAIL', 'LISTENING_MCQ', 20], ['speaking', 'TOPIC_DEVELOPMENT', 'TOPIC_DEVELOPMENT', 2]] as const) for (let i = 1; i <= count; i++) await upsertQuestion(`hcmus:${section}:${i}`, hSecs[section].id, type, topic, 'B1_B2', hExam.id);
  await ensureBlueprint('hcmus-2026-conservative', hcmus.id, 'HCMUS 2026 Conservative Four-Skill Synthetic Practice', 'Synthetic conservative four-skill practice informed only by verified current 2026 timing; not official', 120, 'ACTIVE', hExam.id, [['VOCAB_READING', 'VOCABULARY_READING', 'Vocabulary and reading practice', 20, 'VOCABULARY_MCQ', 'VOCABULARY', 0.28], ['GRAMMAR', 'GRAMMAR_USE_OF_ENGLISH_WRITING', 'Grammar and use practice', 30, 'MCQ_SINGLE_BLANK', 'GRAMMAR', 0.42], ['LISTENING', 'LISTENING', 'Listening practice', 20, 'LISTENING_MCQ', 'LISTENING_DETAIL', 0.28], ['SPEAKING', 'SPEAKING', 'Speaking practice', 2, 'TOPIC_DEVELOPMENT', 'TOPIC_DEVELOPMENT', 0.02]]);
  const result = { scopes: await prisma.learningScope.count({ where: { isActive: true } }), publishedSyntheticQuestions: await prisma.question.count({ where: { status: 'PUBLISHED', contentRole: 'MOCK_EXAM' } }), blueprints: await prisma.examBlueprint.count({ where: { status: 'ACTIVE', provenance: 'SYNTHETIC_MOCK' } }), vstepReadingQuestions: await prisma.question.count({ where: { examId: vExam.id, examSectionId: vSecs.reading.id, status: 'PUBLISHED' } }) }; console.log(JSON.stringify(result));
}
main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
