'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api-client';
import { Card, SectionTitle } from '@/components/ui';
import { StatusBadge, type LearningStatus } from '@/components/study';
import { StudentShell } from '@/components/shells';
interface Topic { id: string; code: string; name: string; category: string; }
interface Stat { topicId: string; attemptCount: number; accuracy: number; masteryScore: number; }
function statusFor(topic: Topic, stats: Stat[]): LearningStatus { const s = stats.find((x) => x.topicId === topic.id); if (!s || s.attemptCount === 0) return 'NOT_STARTED'; if (s.accuracy >= .8 && s.attemptCount >= 5) return 'PASSED'; if (s.accuracy < .7) return 'NEEDS_REVIEW'; return 'IN_PROGRESS'; }
export default function LearnPage() { const [topics, setTopics] = useState<Topic[]>([]); const [stats, setStats] = useState<Stat[]>([]); const [error, setError] = useState<string | null>(null); useEffect(() => { Promise.all([api.listTopics(), api.myStats()]).then(([t, s]) => { setTopics(t as Topic[]); setStats(s as Stat[]); }).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load topics')); return () => undefined; }, []); return <StudentShell><SectionTitle eyebrow="Learning scope" title="Choose a skill" description="Follow a simple loop: learn the idea, check five questions, then continue or review." />{error ? <Card><p role="alert" className="text-rose-700">{error}</p></Card> : !topics.length ? <Card><p className="text-sm text-slate-500">No learning topics are available yet.</p></Card> : <div className="grid gap-4 sm:grid-cols-2">{topics.map((topic) => { const status = statusFor(topic, stats); const stat = stats.find((s) => s.topicId === topic.id); return <Card key={topic.id}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">{topic.category}</p><h2 className="mt-2 text-lg font-bold">{topic.name}</h2></div><StatusBadge status={status} /></div>{stat && <p className="mt-3 text-sm text-slate-500">{Math.round(stat.accuracy * 100)}% accuracy · {stat.attemptCount} answered</p>}<div className="mt-5 flex flex-wrap gap-2"><Link className="inline-flex min-h-10 items-center rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700" href={`/learn/${topic.code}`}>{status === 'NOT_STARTED' ? 'Learn →' : status === 'NEEDS_REVIEW' ? 'Review →' : 'Continue →'}</Link><span className="inline-flex min-h-10 items-center rounded-xl border border-slate-200 px-3 text-xs font-medium text-slate-500">Check 5 questions</span></div></Card>; })}</div>}</StudentShell>; }
