'use client';

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type LearnerLanguage = 'en' | 'vi';
const STORAGE_KEY = 'learner-language';

const en = {
  today: 'Today',
  learn: 'Learn',
  practice: 'Practice',
  strategyDrills: 'Strategy drills',
  speakingWriting: 'Speaking + Writing',
  formatMemory: 'Exam Map',
  formatMemoryDescription: 'Remember the route, timing, and recurring task patterns — not just one question.',
  progressBySection: 'Progress by section',
  mocks: 'Mock exams',
  mistakes: 'Mistakes',
  progress: 'Progress',
  vocabulary: 'Vocabulary',
  meaning: 'Meaning',
  bestFit: 'Best fit',
  contextLabel: 'Context',
  evidence: 'Evidence',
  mainIdea: 'Main idea',
  detail: 'Detail',
  naturalSound: 'Natural sound',
  grammar: 'Grammar',
  structure: 'Structure',
  signal: 'Signal',
  answerChoices: 'Answer choices',
  tileHelper: 'Choose this tile, then explain the signal you noticed.',
  collocation: 'collocation',
  wordFamily: 'word family',
  contrast: 'contrast',
  keySentence: 'key sentence',
  inference: 'inference',
  stress: 'stress',
  chunk: 'chunk',
  shadow: 'shadow',
  signalWord: 'signal word',
  agreement: 'agreement',
  shadowingMode: 'Shadowing mode',
  shadowingHelper: 'Listen, then repeat each chunk aloud.',
  playing: 'Playing…',
  readAloud: 'Read aloud',
  days: (n: number) => `${n} day${n === 1 ? '' : 's'}`,
  examFramework: 'VSTEP',
  targetLevels: 'Target levels: B1/B2',
  hcmusPrep: 'HCMUS-oriented preparation',
  target: 'Preparation profile',
  workspace: 'Workspace',
  streak: 'Study streak',
  logout: 'Log out',
  language: 'Language',
  questionProgress: 'Question progress',
  passage: 'Passage',
  question: 'Question',
  needHint: 'Need a hint?',
  nudge: 'Need a nudge?',
  revealHint: (n: number) => `Reveal hint ${n}`,
  hint: (n: number) => `Hint ${n}`,
  shown: 'shown',
  submitAnswer: 'Submit answer',
  checking: 'Checking…',
  correct: 'Correct',
  incorrect: 'Incorrect',
  niceWork: 'Nice work — your answer is correct.',
  review: 'Let’s learn from this answer.',
  why: 'Why',
  rule: 'Rule / structure',
  example: 'Example',
  commonMistake: 'Common mistake',
  otherAnswers: 'Why the other answers do not work',
  correctAnswer: 'Correct answer',
  next: 'Next question →',
  result: 'See result →',
  retry: 'Retry',
  loading: 'Loading…',
  preparing: 'Preparing…',
  saving: 'Saving…',
  backDashboard: 'Back to Today',
  backMocks: 'Back to mock exams',
  cancel: 'Cancel',
  getStarted: 'Get started',
  focusedPractice: 'Focused practice',
  practiceComplete: 'Practice complete',
  practiceDescription:
    'Choose an answer, use a progressive hint if needed, then read the teaching feedback.',
  reviewDescription: 'Review your answers and turn the tricky ones into your next study step.',
  learnAsAnswer: 'Learn as you answer',
  exitPractice: 'Exit practice',
  reviewAnswers: 'Review answers →',
  reviewLabel: 'Review',
  notebookTitle: 'Your mistake notebook',
  notebookDescription:
    'Revisit tricky questions and turn every wrong answer into a useful insight.',
  notebookClear: 'Your notebook is clear',
  notebookClearDescription:
    'Once you complete a practice session, questions you want to revisit will appear here.',
  startPracticeLabel: 'Start practicing',
  startQuestions: 'Start 5 questions →',
  startPractice: 'Start 5-question set →',
  learningPath: 'Learning path',
  chooseTopic: 'Choose a topic to begin',
  chooseTopicDescription:
    'Start with the area you want to improve. Then choose a focused skill, read the lesson, and take its checkpoint.',
  noTopics: 'No learning topics yet',
  noTopicsDescription: 'Your learning library has not been published yet. Check back soon.',
  selected: 'Selected ✓',
  viewSkills: 'View skills →',
  learningSkill: (n: number) => `${n} learning skill${n === 1 ? '' : 's'} available`,
  skills: 'skills',
  changeTopic: 'Change topic',
  noSkills: 'No skills in this topic yet',
  noSkillsDescription:
    'This topic is ready for content, but no learning scopes have been published.',
  focusedSkill: 'Focused learning skill',
  partOf: (name: string) => `Part of ${name}`,
  checkpoint: (n: number) => `${n} checkpoint${n === 1 ? '' : 's'}`,
  learnAction: 'Learn →',
  reviewAction: 'Review →',
  continueAction: 'Continue →',
  lessonFallback: (name: string) =>
    `Study ${name}: notice the signal words and read the whole sentence before choosing an answer.`,
  learningScope: 'Learning scope',
  focusedLesson: 'Focused lesson',
  learnStep: '1 · Learn',
  checkStep: '2 · Check',
  mentalModel: 'Build a clear mental model',
  remember: 'Remember',
  signalSentence: 'Look for the signal in the sentence.',
  agreementMeaning: 'Check agreement and meaning together.',
  completeSentence: 'Read the complete sentence again.',
  fiveCheckpoint: 'Five-question checkpoint',
  checkpointDescription: 'Your result will tell you whether to continue or review this lesson.',
  checkQuestions: 'Check 5 questions →',
  unablePractice: 'Unable to load practice',
  unableResult: 'Unable to load result',
  missingSession: 'Missing session.',
  practiceResult: 'Practice result',
  mockResult: 'Mock exam result',
  resultSummary: (correct: number, total: number) =>
    `${correct} of ${total} answers correct. Review the gaps, then choose your next focused step.`,
  marked: (value: string) => `Marked: ${value}`,
  markConfidence: 'Mark confidence to schedule a review later.',
  answerReview: 'Answer review',
  vocabularyTitle: 'Vocabulary network',
  vocabularyDescription: 'Learn words through meaning clusters and retrieval, not isolated lists.',
  prototype: 'Prototype · API hook ready',
  cluster: 'Cluster',
  words: (n: number) => `${n} words`,
  wordCard: 'Word card',
  meaningRevealed: 'Meaning revealed',
  recallFirst: 'Recall first',
  revealMeaning: 'Reveal meaning',
  meaningShown: 'Meaning shown',
  sayMeaning: 'Say the meaning aloud before revealing it.',
  synonyms: 'Synonyms',
  antonyms: 'Antonyms',
  collocations: 'Collocations',
  relatedWords: 'Related words',
  again: 'Again',
  nextWord: 'Next word →',
  vocabularyPrototypeNote:
    'Prototype note: review state is intentionally local until the vocabulary API is available; this surface is ready to connect to stored learner progress.',
  unableTopics: 'Unable to load learning topics',
  unableTopic: 'Unable to load lesson',
  unableCheckpoint: 'Unable to start checkpoint',
  missingTopic: 'Missing topic route.',
  lessonDescription: 'Learn the pattern, check your understanding, then keep going.',
  check: 'Check:',
  chooseScope: 'Choose one focused scope. Each lesson ends with a five-question checkpoint.',
  missingPractice: 'Missing practice route.',
  unableSubmit: 'Unable to submit answer',
  unableHint: 'Unable to reveal hint',
  unableToday: 'Unable to load today',
  loadingToday: 'Loading today’s study plan…',
  tryAgain: 'Try again',
  goodMorning: (name: string) => `Good morning, ${name}.`,
  todayDescription: 'Choose one focused next step. You do not need to do everything today.',
  continueLearning: 'Continue learning',
  resumePractice: 'Resume practice →',
  pickUp: 'Pick up your unfinished session',
  buildWin: 'Build your next win',
  questionsLeft: (n: number) => `You have ${n} questions left in this session.`,
  feedbackDescription: 'Start a short focused set and get teaching feedback after every answer.',
  needsReview: 'Needs review',
  questionsRevisit: (n: number) => `${n} question${n === 1 ? '' : 's'} to revisit`,
  caughtUp: 'You are all caught up',
  reviewFresh: 'Review mistakes while the reasoning is still fresh.',
  caughtUpDescription: 'Complete a practice set and this space will guide your next review.',
  practiceMistakes: 'Practice mistakes →',
  practiceNow: 'Practice now →',
  examMode: 'Exam mode',
  startResumeMock: 'Start or resume a mock exam',
  mockDescription:
    'A timed, distraction-free simulation. No hints or explanations until you submit.',
  chooseMock: 'Choose a mock exam →',
  resumeMock: 'Resume mock exam →',
  recentProgress: 'Recent progress',
  noCompleted: 'No completed sessions yet. Your first result will appear here.',
  reviewSession: 'Review this session →',
  focusAreas: 'Focus areas',
  workNext: 'What to work on next',
  seeTopics: 'See all topics →',
  focusEmpty: 'Your focus areas will appear after you answer some questions.',
  attempts: (n: number) => `${n} attempt${n === 1 ? '' : 's'}`,
  mockMode: 'Mock exam mode',
  examSimulation: 'Exam simulation',
  noHints: 'No hints or explanations until final submission.',
  timeRemaining: 'Server time remaining',
  answered: (a: number, t: number) => `Answered ${a} of ${t}`,
  questionNumber: (n: number) => `Question ${n}`,
  savingAnswer: 'Saving answer…',
  answerSaved: 'Answer saved',
  chooseAnswer: 'Choose an answer to save it.',
  previous: '← Previous',
  nextShort: 'Next →',
  submitting: 'Submitting…',
  submitMock: 'Submit mock exam',
  navigator: 'Question navigator',
  answeredHelp: 'Green numbers have an answer. You can change answers before submitting.',
  pauseExit: 'Pause & exit',
  paused: 'PAUSED',
  readyResume: 'Ready to resume?',
  savedDescription: 'Your answers, position, and server-authoritative time are saved.',
  resuming: 'Resuming…',
  mockExpired: 'Mock exam expired',
  expiredDescription: 'The server timer reached zero. Your saved answers are available for review.',
  mockSubmitted: 'Mock exam submitted',
  submittedDescription: 'Your mock exam has already been submitted. Review the score and answers.',
  mockComplete: 'Mock exam complete',
  noQuestions: 'No questions available',
  noQuestionsDescription: 'This mock exam has no questions to display.',
  assessmentMode: 'Assessment mode',
  mockExams: 'Mock exams',
  mockListDescription: 'A timed simulation with no hints or explanations until you submit.',
  noBlueprints: 'No mock exam blueprints are available yet.',
  publishBlueprint: 'Your exam types are ready; an administrator needs to publish a blueprint.',
  versionTiming: (v: string) => `Version ${v} · Exam-style timing and navigation.`,
  questions: (n: number) => `${n} questions`,
  timed: 'Timed',
  beginMock: 'Begin mock exam →',
  progressTitle: 'See your momentum',
  progressDescription:
    'Small improvements compound. Keep your practice consistent and your weak areas visible.',
  overallAccuracy: 'Overall accuracy',
  studyTime: 'Study time',
  sessions: 'Sessions',
  skillBreakdown: 'Skill breakdown',
  thisMonth: 'This month',
  thisWeek: 'this week',
  loginWelcome: 'Welcome back',
  continueProgress: 'Continue your progress',
  signInDescription: 'Sign in to pick up exactly where you left off.',
  email: 'Email',
  password: 'Password',
  signingIn: 'Signing in…',
  signIn: 'Sign in',
  newTo: 'New to Elevate?',
  createAccount: 'Create an account',
  loginFailed: 'Login failed',
  register: 'Register',
  name: 'Name',
  studyTarget: 'Study Target (optional)',
  pickLater: '-- pick later --',
  creating: 'Creating...',
  createAccountButton: 'Create account',
  registerFailed: 'Register failed',
  mistakesTitle: 'Your mistakes',
  mistakesDescription: (n: number) =>
    `${n} distinct question${n === 1 ? '' : 's'} answered incorrectly.`,
  startMistakeReview: 'Start mistake review',
  starting: 'Starting...',
  noMistakes: 'No mistakes yet — take some practice runs.',
  answer: 'Answer:',
  backDashboardLong: 'Back to dashboard',
  score: 'Score',
  questionsLabel: 'Questions',
  reviewMistakes: 'Review mistakes →',
  practiceWeak: 'Practice weak topics →',
  practiceAnother: 'Practice another set',
} as const;

type LearnerCopy = {
  [K in keyof typeof en]: (typeof en)[K] extends (...args: infer A) => infer R
    ? (...args: A) => R
    : string;
};
const vi: Partial<LearnerCopy> = {
  today: 'Hôm nay',
  learn: 'Học',
  practice: 'Luyện tập',
  strategyDrills: 'Luyện chiến lược',
  speakingWriting: 'Nói + Viết',
  mocks: 'Đề thi thử',
  mistakes: 'Cần ôn lại',
  progress: 'Tiến độ',
  vocabulary: 'Từ vựng',
  meaning: 'Nghĩa',
  bestFit: 'Phù hợp nhất',
  contextLabel: 'Ngữ cảnh',
  evidence: 'Bằng chứng',
  mainIdea: 'Ý chính',
  detail: 'Chi tiết',
  naturalSound: 'Âm thanh tự nhiên',
  grammar: 'Ngữ pháp',
  structure: 'Cấu trúc',
  signal: 'Dấu hiệu',
  answerChoices: 'Các lựa chọn trả lời',
  tileHelper: 'Chọn thẻ này, sau đó giải thích dấu hiệu bạn nhận thấy.',
  collocation: 'cụm từ',
  wordFamily: 'họ từ',
  contrast: 'đối chiếu',
  keySentence: 'câu then chốt',
  inference: 'suy luận',
  stress: 'trọng âm',
  chunk: 'cụm',
  shadow: 'bắt chước',
  signalWord: 'từ dấu hiệu',
  agreement: 'sự hòa hợp',
  shadowingMode: 'Chế độ bắt chước',
  shadowingHelper: 'Nghe rồi lặp lại từng cụm thành tiếng.',
  playing: 'Đang phát…',
  readAloud: 'Đọc thành tiếng',
  days: (n: number) => `${n} ngày`,
  examFramework: 'VSTEP',
  targetLevels: 'Mục tiêu trình độ: B1/B2',
  hcmusPrep: 'Ôn tập theo định hướng HCMUS',
  target: 'Hồ sơ ôn tập',
  workspace: 'Khu học tập',
  streak: 'Chuỗi ngày học',
  logout: 'Đăng xuất',
  language: 'Ngôn ngữ',
  questionProgress: 'Tiến độ câu hỏi',
  passage: 'Đoạn văn',
  question: 'Câu hỏi',
  needHint: 'Cần gợi ý?',
  nudge: 'Cần một gợi ý nhỏ?',
  revealHint: (n: number) => `Xem gợi ý ${n}`,
  hint: (n: number) => `Gợi ý ${n}`,
  shown: 'đã xem',
  submitAnswer: 'Nộp câu trả lời',
  checking: 'Đang kiểm tra…',
  correct: 'Đúng',
  incorrect: 'Chưa đúng',
  niceWork: 'Tốt lắm — câu trả lời của bạn chính xác.',
  review: 'Hãy cùng rút kinh nghiệm từ câu này.',
  why: 'Vì sao',
  rule: 'Quy tắc / cấu trúc',
  example: 'Ví dụ',
  commonMistake: 'Lỗi thường gặp',
  otherAnswers: 'Vì sao các đáp án khác chưa phù hợp',
  correctAnswer: 'Đáp án đúng',
  next: 'Câu tiếp theo →',
  retry: 'Thử lại',
  loading: 'Đang tải…',
  preparing: 'Đang chuẩn bị…',
  saving: 'Đang lưu…',
  backDashboard: 'Quay lại Hôm nay',
  backMocks: 'Quay lại đề thi thử',
  cancel: 'Hủy',
  getStarted: 'Bắt đầu',
  focusedPractice: 'Luyện tập có trọng tâm',
  practiceComplete: 'Hoàn thành luyện tập',
  practiceDescription: 'Chọn đáp án, dùng gợi ý tăng dần nếu cần, rồi đọc phản hồi hướng dẫn.',
  reviewDescription: 'Xem lại câu trả lời và biến phần khó thành bước học tiếp theo.',
  learnAsAnswer: 'Học qua từng câu trả lời',
  exitPractice: 'Thoát luyện tập',
  reviewAnswers: 'Xem lại câu trả lời →',
  reviewLabel: 'Ôn tập',
  notebookTitle: 'Sổ tay câu sai',
  notebookDescription: 'Xem lại câu hỏi khó và biến mỗi đáp án sai thành một hiểu biết hữu ích.',
  notebookClear: 'Sổ tay của bạn đang trống',
  notebookClearDescription:
    'Sau khi hoàn thành một phiên luyện tập, các câu hỏi cần xem lại sẽ xuất hiện ở đây.',
  startPracticeLabel: 'Bắt đầu luyện tập',
  startQuestions: 'Làm 5 câu hỏi →',
  startPractice: 'Bắt đầu bộ 5 câu →',
  learningPath: 'Lộ trình học',
  chooseTopic: 'Chọn chủ đề để bắt đầu',
  chooseTopicDescription:
    'Bắt đầu với phần bạn muốn cải thiện. Sau đó chọn kỹ năng, đọc bài học và làm bài kiểm tra.',
  noTopics: 'Chưa có chủ đề học tập',
  noTopicsDescription: 'Thư viện học tập chưa được xuất bản. Hãy quay lại sau.',
  selected: 'Đã chọn ✓',
  viewSkills: 'Xem kỹ năng →',
  learningSkill: (n: number) => `${n} kỹ năng học tập có sẵn`,
  skills: 'kỹ năng',
  changeTopic: 'Đổi chủ đề',
  noSkills: 'Chưa có kỹ năng trong chủ đề này',
  noSkillsDescription: 'Chủ đề đã sẵn sàng nhưng chưa có phạm vi học tập được xuất bản.',
  focusedSkill: 'Kỹ năng học tập trọng tâm',
  partOf: (name: string) => `Thuộc ${name}`,
  checkpoint: (n: number) => `${n} lần kiểm tra`,
  learnAction: 'Học →',
  reviewAction: 'Ôn lại →',
  continueAction: 'Tiếp tục →',
  learningScope: 'Phạm vi học tập',
  focusedLesson: 'Bài học trọng tâm',
  learnStep: '1 · Học',
  checkStep: '2 · Kiểm tra',
  mentalModel: 'Xây dựng mô hình tư duy rõ ràng',
  remember: 'Ghi nhớ',
  signalSentence: 'Tìm dấu hiệu trong câu.',
  agreementMeaning: 'Kiểm tra cả sự hòa hợp và ý nghĩa.',
  completeSentence: 'Đọc lại toàn bộ câu.',
  fiveCheckpoint: 'Bài kiểm tra 5 câu',
  checkpointDescription: 'Kết quả sẽ cho biết bạn nên tiếp tục hay ôn lại bài học.',
  checkQuestions: 'Làm 5 câu kiểm tra →',
  unablePractice: 'Không thể tải bài luyện tập',
  unableResult: 'Không thể tải kết quả',
  missingSession: 'Thiếu phiên học.',
  practiceResult: 'Kết quả luyện tập',
  mockResult: 'Kết quả đề thi thử',
  resultSummary: (correct: number, total: number) =>
    `Bạn trả lời đúng ${correct}/${total} câu. Hãy xem lại phần còn thiếu rồi chọn bước học tiếp theo.`,
  marked: (value: string) => `Đã đánh dấu: ${value}`,
  markConfidence: 'Đánh dấu mức độ chắc chắn để lên lịch ôn tập sau.',
  answerReview: 'Xem lại câu trả lời',
  vocabularyTitle: 'Mạng lưới từ vựng',
  vocabularyDescription:
    'Học từ qua các cụm nghĩa và hoạt động truy hồi, không học theo danh sách rời rạc.',
  prototype: 'Bản thử nghiệm · Sẵn sàng kết nối API',
  cluster: 'Cụm từ',
  words: (n: number) => `${n} từ`,
  wordCard: 'Thẻ từ',
  meaningRevealed: 'Đã hiển thị nghĩa',
  recallFirst: 'Hãy nhớ trước',
  revealMeaning: 'Hiển thị nghĩa',
  meaningShown: 'Đã hiển thị nghĩa',
  sayMeaning: 'Hãy tự nói nghĩa tiếng Anh trước khi xem.',
  synonyms: 'Từ đồng nghĩa',
  antonyms: 'Từ trái nghĩa',
  collocations: 'Cụm từ thường dùng',
  relatedWords: 'Từ liên quan',
  again: 'Lại lần nữa',
  nextWord: 'Từ tiếp theo →',
  vocabularyPrototypeNote:
    'Ghi chú bản thử nghiệm: trạng thái ôn tập hiện được lưu cục bộ cho đến khi có API từ vựng; giao diện đã sẵn sàng kết nối với tiến độ học.',
  unableTopics: 'Không thể tải chủ đề học tập',
  unableTopic: 'Không thể tải bài học',
  unableCheckpoint: 'Không thể bắt đầu bài kiểm tra',
  missingTopic: 'Thiếu đường dẫn chủ đề.',
  lessonDescription: 'Học quy tắc, kiểm tra mức độ hiểu và tiếp tục tiến bộ.',
  check: 'Kiểm tra:',
  chooseScope: 'Chọn một phạm vi trọng tâm. Mỗi bài học kết thúc bằng bài kiểm tra 5 câu.',
  missingPractice: 'Thiếu đường dẫn luyện tập.',
  unableSubmit: 'Không thể nộp câu trả lời',
  unableHint: 'Không thể hiển thị gợi ý',
  unableToday: 'Không thể tải nội dung hôm nay',
  loadingToday: 'Đang tải kế hoạch học hôm nay…',
  tryAgain: 'Thử lại',
  goodMorning: (name: string) => `Chào buổi sáng, ${name}.`,
  todayDescription: 'Chọn một bước tiếp theo có trọng tâm. Bạn không cần làm mọi thứ hôm nay.',
  continueLearning: 'Tiếp tục học',
  resumePractice: 'Tiếp tục luyện tập →',
  pickUp: 'Tiếp tục phiên học dang dở',
  buildWin: 'Tạo tiến bộ tiếp theo',
  questionsLeft: (n: number) => `Bạn còn ${n} câu hỏi trong phiên này.`,
  feedbackDescription: 'Bắt đầu một bộ câu hỏi ngắn và nhận phản hồi sau mỗi câu.',
  needsReview: 'Cần ôn lại',
  questionsRevisit: (n: number) => `${n} câu hỏi cần xem lại`,
  caughtUp: 'Bạn đã hoàn tất mọi việc',
  reviewFresh: 'Ôn lại lỗi khi cách suy luận còn rõ ràng.',
  caughtUpDescription: 'Hoàn thành một bộ luyện tập để nhận hướng dẫn ôn tiếp theo.',
  practiceMistakes: 'Luyện câu sai →',
  practiceNow: 'Luyện tập ngay →',
  examMode: 'Chế độ thi',
  startResumeMock: 'Bắt đầu hoặc tiếp tục đề thi thử',
  mockDescription:
    'Mô phỏng có giới hạn thời gian, không bị xao nhãng. Không có gợi ý hay giải thích trước khi nộp bài.',
  chooseMock: 'Chọn đề thi thử →',
  resumeMock: 'Tiếp tục đề thi thử →',
  recentProgress: 'Tiến độ gần đây',
  noCompleted: 'Chưa có phiên nào hoàn thành. Kết quả đầu tiên sẽ xuất hiện ở đây.',
  reviewSession: 'Xem lại phiên này →',
  focusAreas: 'Khu vực trọng tâm',
  workNext: 'Nên học gì tiếp theo',
  seeTopics: 'Xem tất cả chủ đề →',
  focusEmpty: 'Khu vực trọng tâm sẽ xuất hiện sau khi bạn trả lời một số câu hỏi.',
  attempts: (n: number) => `${n} lần làm`,
  mockMode: 'Chế độ thi thử',
  examSimulation: 'Mô phỏng kỳ thi',
  noHints: 'Không có gợi ý hay giải thích cho đến khi nộp bài.',
  timeRemaining: 'Thời gian còn lại trên máy chủ',
  answered: (a: number, t: number) => `Đã trả lời ${a}/${t}`,
  questionNumber: (n: number) => `Câu hỏi ${n}`,
  savingAnswer: 'Đang lưu câu trả lời…',
  answerSaved: 'Đã lưu câu trả lời',
  chooseAnswer: 'Chọn câu trả lời để lưu.',
  previous: '← Trước',
  nextShort: 'Tiếp →',
  submitting: 'Đang nộp…',
  submitMock: 'Nộp bài thi thử',
  navigator: 'Danh sách câu hỏi',
  answeredHelp: 'Các số màu xanh đã có câu trả lời. Bạn có thể đổi đáp án trước khi nộp.',
  pauseExit: 'Tạm dừng & thoát',
  paused: 'ĐÃ TẠM DỪNG',
  readyResume: 'Sẵn sàng tiếp tục?',
  savedDescription: 'Câu trả lời, vị trí và thời gian theo máy chủ đã được lưu.',
  resuming: 'Đang tiếp tục…',
  mockExpired: 'Đề thi thử đã hết giờ',
  expiredDescription: 'Đồng hồ máy chủ đã về 0. Các câu trả lời đã lưu sẵn sàng để xem lại.',
  mockSubmitted: 'Đã nộp đề thi thử',
  submittedDescription: 'Đề thi thử đã được nộp. Hãy xem điểm và câu trả lời.',
  mockComplete: 'Hoàn thành đề thi thử',
  noQuestions: 'Không có câu hỏi',
  noQuestionsDescription: 'Đề thi thử này không có câu hỏi để hiển thị.',
  assessmentMode: 'Chế độ đánh giá',
  mockExams: 'Đề thi thử',
  mockListDescription:
    'Mô phỏng có giới hạn thời gian, không có gợi ý hay giải thích trước khi nộp.',
  noBlueprints: 'Chưa có đề thi thử nào.',
  publishBlueprint: 'Loại kỳ thi của bạn đã sẵn sàng; quản trị viên cần xuất bản đề.',
  versionTiming: (v: string) => `Phiên bản ${v} · Thời gian và điều hướng theo kiểu đề thi.`,
  questions: (n: number) => `${n} câu hỏi`,
  timed: 'Có giờ',
  beginMock: 'Bắt đầu đề thi thử →',
  progressTitle: 'Xem đà tiến bộ',
  progressDescription: 'Những tiến bộ nhỏ sẽ tích lũy. Hãy luyện tập đều đặn và theo dõi điểm yếu.',
  overallAccuracy: 'Độ chính xác tổng thể',
  studyTime: 'Thời gian học',
  sessions: 'Phiên học',
  skillBreakdown: 'Phân tích kỹ năng',
  thisMonth: 'Tháng này',
  thisWeek: 'tuần này',
  loginWelcome: 'Chào mừng trở lại',
  continueProgress: 'Tiếp tục tiến độ',
  signInDescription: 'Đăng nhập để tiếp tục đúng nơi bạn đã dừng.',
  email: 'Email',
  password: 'Mật khẩu',
  signingIn: 'Đang đăng nhập…',
  signIn: 'Đăng nhập',
  newTo: 'Mới dùng Elevate?',
  createAccount: 'Tạo tài khoản',
  loginFailed: 'Đăng nhập thất bại',
  register: 'Đăng ký',
  name: 'Tên',
  studyTarget: 'Mục tiêu học (không bắt buộc)',
  pickLater: '-- chọn sau --',
  creating: 'Đang tạo...',
  createAccountButton: 'Tạo tài khoản',
  registerFailed: 'Đăng ký thất bại',
  mistakesTitle: 'Các câu sai',
  mistakesDescription: (n: number) => `${n} câu hỏi riêng biệt đã trả lời sai.`,
  startMistakeReview: 'Bắt đầu ôn câu sai',
  starting: 'Đang bắt đầu...',
  noMistakes: 'Chưa có câu sai — hãy làm một vài lượt luyện tập.',
  answer: 'Đáp án:',
  backDashboardLong: 'Quay lại bảng điều khiển',
  score: 'Điểm',
  questionsLabel: 'Câu hỏi',
  progressBySection: 'Tiến độ theo phần',
  reviewMistakes: 'Ôn câu sai →',
  practiceWeak: 'Luyện chủ đề yếu →',
  practiceAnother: 'Làm bộ khác',
  formatMemory: 'Bản đồ cấu trúc đề',
  formatMemoryDescription: 'Ghi nhớ trình tự, thời lượng và dạng bài lặp lại — không chỉ từng câu hỏi.',
  progressBySection: 'Tiến độ theo phần',
};

export const learnerCopy = { en, vi: { ...en, ...vi } } as const;
export function getLearnerCopy(language: LearnerLanguage) {
  return learnerCopy[language] ?? learnerCopy.en;
}

const LanguageContext = createContext<{
  language: LearnerLanguage;
  setLanguage: (language: LearnerLanguage) => void;
}>({ language: 'en', setLanguage: () => undefined });
export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LearnerLanguage>('en');
  useEffect(() => {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved === 'en' || saved === 'vi') setLanguageState(saved);
  }, []);
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);
  function setLanguage(next: LearnerLanguage) {
    setLanguageState(next);
    window.localStorage.setItem(STORAGE_KEY, next);
  }
  const value = useMemo(() => ({ language, setLanguage }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage() {
  return useContext(LanguageContext);
}
